[package]
name = "cosmic-time"
version = "0.2.0"
edition = "2021"
description = "An animation Crate for Iced and Cosmic DE"
authors = ["Brock Szuszczewicz <brock@szu.email>"]
license = "MIT"
repository = "https://github.com/pop-os/cosmic-time"
documentation = "https://docs.rs/cosmic-time"
keywords = ["gui", "animation", "interface", "widgets", "iced"]
categories = ["gui"]

[workspace]
members = [
    "examples/*",
]

[dependencies]
iced = { version = "0.9.0", features = [ "tokio" ] }
iced_native = "0.10.1"
iced_futures = "0.6.0"
iced_core = "0.9.0"
iced_style = "0.8.0"
