[package]
name = "cosmic-time"
version = "0.2.0"
edition = "2021"
description = "An animation Crate for Iced and Cosmic DE"
authors = ["Brock Szuszczewicz <brock@szu.email>"]
license = "MIT"
repository = "https://github.com/pop-os/cosmic-time"
documentation = "https://docs.rs/cosmic-time"
keywords = ["gui", "animation", "interface", "widgets", "iced"]
categories = ["gui"]

[features]
default = ["libcosmic"]
libcosmic = ["dep:libcosmic"]
iced = ["dep:iced", "dep:iced_native", "dep:iced_futures", "dep:iced_core", "dep:iced_style"]
once_cell = ["dep:once_cell"]

[workspace]
members = [
    "examples/*",
]

[dependencies]
iced = { version = "0.9.0", features = [ "tokio" ], optional = true }
iced_native = { version = "0.10.1", optional = true }
iced_futures = { version = "0.6.0", optional = true }
iced_core = { version = "0.9.0", optional = true }
iced_style = { version = "0.8.0", optional = true }
libcosmic = { git = "https://github.com/pop-os/libcosmic/", default-features = false, features = [ "tokio" ], optional = true }
once_cell = { version = "1.18.0", optional = true }
