name: Audit
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - uses: actions/checkout@master
    - name: Audit dependencies
      run: cargo audit
