name: Lint
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy
    - uses: actions/checkout@master
    - name: Check lints iced
      run: cargo clippy --workspace --no-default-features --features=once_cell --all-targets --no-deps -- -D warnings
    - name: Check lints wayland-libcosmic
      run: cargo clippy --no-default-features --features=wayland-libcosmic --all-targets --no-deps -- -D warnings
    - name: Check lints winit-libcosmic
      run: cargo clippy --no-default-features --features=winit-libcosmic --all-targets --no-deps -- -D warnings